/*
LOS ENUNCIADOS DE LOS EJERCICIOS ESTAN EN EL ARCHIVO EJERCICIOS PROPUESTOS Y RESUELTOS EN CPP.PDF.

NOTAR: TODOS LOS EJERCICIOS LOS TRABAJARE CON FUNCIONES AGREGANDO LA FUNCION PRINCIPAL PARA MEJOR EFECTIVIDAD.

EVITARE: Uso del "using namespace std;" ya que en proyectos grandes ayuda a ordenar el codigo.
*/

#include <iostream>
#include <math.h>

